### PR TITLE
Drop bee larva via kubejs instead of loot tables

### LINKED ISSUE #4948: Have baby bees drop larva as well
### Describe your suggestion

https://github.com/EnigmaticaModpacks/Enigmatica6/blob/develop/kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/resourcefulbees/bees.js

### Why would you like this added/changed?

Currently only grown-up bees drop larva, leaving a window open for bees that meet their end before they can come of age.

### LINKED ISSUE #5095: Scavenger can dupe Larvae
### Modpack Version

v1.4,1

### Describe your issue.

pretty explanatory i think. any bee that can be killed can be duped with the scavenger enchantment. i do not know if this is intentional or not, but i just thought i'd mention this!

### Crash Report

_No response_

### Latest Log

_No response_

### Have you modified the modpack?

Yes

### User Modifications

Rubidium and Rubidium Extras. I don't think these mess with scavenger but one never knows.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### PR DESCRIPTION
**Pull request by Quezler**
as discussed in ye old bee larva thread 🐝 

- fixes #5095
- fixes #4948

- the 4 commented console.logs are left there intentionally to make it easier to work there in the future
- the `{` and `}` ensure the `bee_map` constant cannot escape into other kubejs files
- done in a generic file so all (future) entity deaths can reuse the same handler

### CODE REVIEW

File: kubejs/server_scripts/enigmatica/kubejs/base/entity/on_death.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
+{
+  const bee_map = {}
```
Comment (NielsPilgaard) [inline kubejs/server_scripts/enigmatica/kubejs/base/entity/on_death.js:2]: I'd prefer this const inside the `onEvent` call, that's how we usually do with non-global consts

**Review by NielsPilgaard — APPROVED** [review]

File: kubejs/server_scripts/enigmatica/kubejs/base/entity/on_death.js (hunk 1 above)
Comment (Quezler) [reply kubejs/server_scripts/enigmatica/kubejs/base/entity/on_death.js:2]: but then it would get redefined **each time** any mob dies, better to initialize the map outside the death event  👀

Comment (NielsPilgaard) [reply kubejs/server_scripts/enigmatica/kubejs/base/entity/on_death.js:2]: Very valid point 👍
